# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flashy-TableViews-Lab' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'APParallaxHeader'
  # Pods for Flashy-TableViews-Lab

  #target 'Flashy-TableViews-LabTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'Flashy-TableViews-LabUITests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
